<?php

/**
 * @file
 * Uses best practices to check for pre-launch best practices.
 */

use Drupal\checklistapi\ChecklistapiChecklist;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_checklistapi_checklist_info().
 *
 * @see _launch_checklist_preprocess_checklist_items()
 */
function launch_checklist_checklistapi_checklist_info() {
  $definitions = [];
  $definitions['launch_checklist'] = [
    '#title' => t('Launch checklist'),
    '#description' => t('Keep track of your pre-launch tasks.'),
    '#path' => '/admin/config/development/launch-checklist',
    '#callback' => 'launch_checklist_checklistapi_checklist_items',
    '#help' => t("<p>Check off each task as you complete it. Don't forget to click the <em>Save</em> button!</p>"),
  ];
  return $definitions;
}

/**
 * Implements callback_checklistapi_checklist_items() for launch_checklist.
 */
function launch_checklist_checklistapi_checklist_items() {
  // Home page.
  $front_route = Url::fromRoute('<front>');
  // Check if module exists.
  $moduleHandler = \Drupal::service('module_handler');
  // Webform.
  $webform_route = '';
  $webform_route = Url::fromUri('https://www.drupal.org/project/webform');
  if ($moduleHandler->moduleExists('webform')) {
    $webform_route = Url::fromRoute('entity.webform.collection');
  }
   // Google Analytics.
   $google_analytics_route = '';
   $google_analytics_route = Url::fromUri('https://www.drupal.org/project/google_analytics');
   if ($moduleHandler->moduleExists('google_analytics')) {
     $google_analytics_route = Url::fromRoute('google_analytics.admin_settings_form');
   }

  return [
    // Section 1 General.
    '01_general' => [
      '#title' => t('General'),
      '#description' => t('<p>General settings for the Drupal site.</p>'),
      'site_information_email' => [
        '#title' => t('Verify the site information uses client email'),
        '#description' => t('The From address in automated emails sent during registration and new password requests, and other notifications.'),
        'handbook_page' => [
          '#text' => t('Site Information Email'),
          '#url' => Url::fromRoute('system.site_information_settings'),
        ],
      ],
      'site_information_name' => [
        '#title' => t('Verify the site title tag is correct'),
        '#description' => t('Make sure the Site name field is correct.'),
        'handbook_page' => [
          '#text' => t('Site Information Name'),
          '#url' => Url::fromRoute('system.site_information_settings'),
        ],
      ],
      'favicon' => [
        '#title' => t('Favicon'),
        '#description' => t('Verify Favicon is correct.'),
        'handbook_page' => [
          '#text' => t('Front page of site.'),
          '#url' => $front_route,
        ],
      ],
    ],
    // Section 2 Browser Checks.
    '02_browser_checks' => [
      '#title' => t('Browser Checks'),
      '#description' => t('<p>Verify the look and funcitonality across devices.</p>'),
      'desktop' => [
        '#title' => t('Verify the site looks and behaves as exprected on Desktop'),
        '#description' => t('Test on the latest two versions of browsers, including Google Chrome, Mozilla Firefox, Safari, Internet Explorer, Edge and Opera'),
        'handbook_page' => [
          '#text' => t('Use a Cross Browser Testing Tool like Browserstack'),
          '#url' => Url::fromUri('https://www.browserstack.com/'),
        ],
      ],
      'mobile' => [
        '#title' => t('Verify the site looks and behaves as exprected on mobile'),
        '#description' => t('Testing should also be completed on mobile devices including: Apple iPad, Apple iPhone, Samsung Galaxy SIII, Nexus, Google Nexus 7, Amazon Kindle Fire, Droid Razr 4G, Blackberry, Amazon Silk'),
        'handbook_page' => [
          '#text' => t('Use a Cross Browser Testing Tool like Browserstack'),
          '#url' => Url::fromUri('https://www.browserstack.com/'),
        ],
      ],
    ],
    // Section 3 Forms.
    '03_forms' => [
      '#title' => t('Forms'),
      '#description' => t('<p>Verify forms work as expected.</p>'),
      'email' => [
        '#title' => t('Form emails'),
        '#description' => t('Check all webforms for recipient email and test.'),
        'handbook_page' => [
          '#text' => t('Webform'),
          '#url' => $webform_route,
        ],
      ],
      'confirmation' => [
        '#title' => t('Form confirmation'),
        '#description' => t('Check all webforms for thank you message'),
        'handbook_page' => [
          '#text' => t('Webform'),
          '#url' => $webform_route,
        ],
      ],
      'spam' => [
        '#title' => t('Spam protection'),
        '#description' => t('Ensure Spam prevention measures are in place.'),
      ],
    ],
    // Section 4 SEO.
    '04_seo' => [
      '#title' => t('SEO'),
      '#description' => t('<p>SEO settings for the Drupal site.</p>'),
      'analytics' => [
        '#title' => t('Analytics'),
        '#description' => t('Verify Google Analytics or similar is installed and correct access has been given'),
        'handbook_page' => [
          '#text' => t('Google Analytics module'),
          '#url' => $google_anaytics_route,
        ],
      ],
      'xml_sitemap' => [
        '#title' => t('Verify the site title tag is correct'),
        '#description' => t('Make sure the Site name field is correct.'),
        'handbook_page' => [
          '#text' => t('Site Information Name'),
          '#url' => Url::fromRoute('system.site_information_settings'),
        ],
      ],
      'favicon' => [
        '#title' => t('Favicon'),
        '#description' => t('Verify Favicon is correct.'),
        'handbook_page' => [
          '#text' => t('Front page of site.'),
          '#url' => $front_route,
        ],
      ],
    ],
  ];
}
