<?php

/**
 * @file
 * Uses best practices to check for pre-launch best practices.
 */

use Drupal\Core\Url;
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_01.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_02.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_03.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_04.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_05.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_06.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_07.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_08.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_09.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_10.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_11.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_12.inc';
include drupal_get_path('module', 'launch_checklist') . '/inc/checklist_section_13.inc';

/**
 * Implements hook_checklistapi_checklist_info().
 *
 * @see _launch_checklist_preprocess_checklist_items()
 */
function launch_checklist_checklistapi_checklist_info() {
  $definitions = [];
  $definitions['launch_checklist'] = [
    '#title' => t('Launch checklist'),
    '#description' => t('Keep track of your pre-launch tasks.'),
    '#path' => '/admin/config/development/launch-checklist',
    '#callback' => 'launch_checklist_checklistapi_checklist_items',
    '#help' => t("<p>Check off each task as you complete it. Don't forget to click the <em>Save</em> button!</p>"),
  ];
  return $definitions;
}

/**
 * Implements callback_checklistapi_checklist_items() for launch_checklist.
 */
function launch_checklist_checklistapi_checklist_items() {
  // Home page.
  $front_route = Url::fromRoute('<front>');
  // Check if module exists.
  $moduleHandler = \Drupal::service('module_handler');
  // Webform.
  $webform_route = '';
  $webform_route = Url::fromUri('https://www.drupal.org/project/webform');
  if ($moduleHandler->moduleExists('webform')) {
    $webform_route = Url::fromRoute('entity.webform.collection');
  }
  // Google Analytics.
  $google_analytics_route = '';
  $google_analytics_route = Url::fromUri('https://www.drupal.org/project/google_analytics');
  if ($moduleHandler->moduleExists('google_analytics')) {
    $google_analytics_route = Url::fromRoute('google_analytics.admin_settings_form');
  }
  // XML Sitemap.
  $xml_sitemap = '';
  $xml_sitemap = Url::fromUri('https://www.drupal.org/project/xmlsitemap');
  if ($moduleHandler->moduleExists('xmlsitemap')) {
    $xml_sitemap = Url::fromRoute('xmlsitemap.admin_search');
  }
  // Global Redirect module.
  $global_redirect = '';
  $global_redirect = Url::fromUri('https://www.drupal.org/project/globalredirect');
  if ($moduleHandler->moduleExists('globalredirect')) {
    $global_redirect = Url::fromRoute('xmlsitemap.admin_search');
  }

  // Populate the array with content sections and return the whole thing.
  $sections_array = [];
  $sections_array ["01_general"]        = populate_section_01();
  $sections_array ["02_browser"]        = populate_section_02();
  $sections_array ["03_forms"]          = populate_section_03();
  $sections_array ["04_seo"]            = populate_section_04();
  $sections_array ["05_permissions"]    = populate_section_05();
  $sections_array ["06_content"]        = populate_section_06();
  $sections_array ["07_gdpr_privacy"]   = populate_section_07();
  $sections_array ["08_security"]       = populate_section_08();
  $sections_array ["09_database"]       = populate_section_09();
  $sections_array ["10_theme"]          = populate_section_10();
  $sections_array ["11_accessibility"]  = populate_section_11();
  $sections_array ["12_drupal_modules"] = populate_section_12();
  $sections_array ["13_other"]          = populate_section_13();
  return $sections_array;

}


